#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

./configure \
	--prefix=/usr \
	--enable-cxx     \
	--disable-static \
	--docdir=/usr/share/doc/"$program_name-$version"

make -j"$(NPROC)"
make html

make DESTDIR="$pkg" install
make DESTDIR="$pkg" install-html

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
for f in COPYING COPYINGv2 COPYINGv3 COPYING.LESSERv3 README; do
	install -Dm0644 "${f}" \
		"$pkg/usr/share/doc/$program_name-$version"
done

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

