#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.gz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.gz"
cd "$program_name-$version"

chown root:root -R .

mkdir build
cd build

../configure \
	--prefix=/usr \
	--sysconfdir=/etc       \
	--enable-elf-shlibs     \
	--disable-libblkid      \
	--disable-libuuid       \
	--disable-uuidd         \
	--disable-fsck

make -j"${NPROC}"

make DESTDIR="$pkg" install

rm -fv "$pkg"/usr/lib/{libcom_err,libe2p,libext2fs,libss}.a

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
	-e "shared object" | grep ELF | cut -d : -f 1 | \
	xargs strip --strip-unneeded 2> /dev/null || true

if [ -d "$pkg/usr/lib" ]; then
	find "$pkg"/usr/lib -name \*.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
	find "$pkg"/usr/libexec -name \*.la -delete
fi

install -dm0755 -o root -g root \
	"$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 "$cwd"/files/MIT-LICENSE \
	"$pkg/usr/share/doc/$program_name-$version/"

install -dm0755 -o root -g root \
	"$pkg/usr/share/doc/info"
gunzip -v "$pkg"/usr/share/info/libext2fs.info.gz
install-info --dir-file="$pkg"/usr/share/info/dir \
	"$pkg"/usr/share/info/libext2fs.info

makeinfo -o doc/com_err.info ../lib/et/com_err.texinfo
install -v -m0644 doc/com_err.info "$pkg"/usr/share/info
install-info --dir-file="$pkg"/usr/share/info/dir \
	"$pkg"/usr/share/info/com_err.info

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name/files"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"
cp files/* \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/files/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

