#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.gz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.gz"
cd "$program_name-$version"

chown root:root -R .

./configure \
	--prefix=/usr \
	--disable-static \
	--docdir=/usr/share/doc/"$program_name-$version"

make -j"${NPROC}"
make html

make DESTDIR="$pkg" install

make DESTDIR="$pkg" install-html

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
        -e "shared object" | grep ELF | cut -d : -f 1 | \
        xargs strip --strip-unneeded 2> /dev/null || true

if [ -d "$pkg/usr/lib" ]; then
        find "$pkg"/usr/lib -name \*.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
        find "$pkg"/usr/libexec -name \*.la -delete
fi

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
for f in COPYING.LESSER README; do
	install -Dm0644 "${f}" \
		"$pkg/usr/share/doc/$program_name-$version"
done


mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

