#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

sed -i 's/groups$(EXEEXT) //' src/Makefile.in
find man -name Makefile.in -exec sed -i 's/groups\.1 / /' {} \;
find man -name Makefile.in -exec sed -i 's/getspnam\.3 / /' {} \;
find man -name Makefile.in -exec sed -i 's/passwd\.5 / /' {} \;

sed -e 's:#ENCRYPT_METHOD DES:ENCRYPT_METHOD SHA512:' \
	-e 's@#\(SHA_CRYPT_..._ROUNDS 5000\)@\100@' \
	-e 's:/var/spool/mail:/var/mail:' \
	-e '/PATH=/{s@/sbin:@@;s@/bin:@@}' \
	-i etc/login.defs

install -dm0755 -o root -g root "$pkg/usr/bin"
echo "" > "$pkg/usr/bin/passwd"

./configure \
	--sysconfdir=/etc \
	--disable-static  \
	--with-group-name-max-length=32

make -j"${NPROC}"

make DESTDIR="$pkg" exec_prefix=/usr install
make DESTDIR="$pkg" -C man install-man

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
	-e "shared object" | grep ELF | cut -d : -f 1 | \
	xargs strip --strip-unneeded 2> /dev/null || true

if [ -d "$pkg/usr/lib" ]; then
	find "$pkg"/usr/lib -name \*.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
	find "$pkg"/usr/libexec -name \*.la -delete
fi

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 COPYING \
	"$pkg/usr/share/doc/$program_name-$version/"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description post-install sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

