#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

mkdir build
cd build

../configure \
	--prefix=/usr \
	--sysconfdir=/etc   \
	--enable-gold       \
	--enable-ld=default \
	--enable-plugins    \
	--enable-shared     \
	--disable-werror    \
	--enable-64-bit-bfd \
	--with-system-zlib

make -j"$(NPROC)" tooldir=/usr

make DESTDIR="$pkg" tooldir=/usr install

rm -fv "$pkg"/usr/lib/lib{bfd,ctf,ctf-nobfd,sframe,opcodes}.a
rm -fv "$pkg"/usr/share/man/man1/{gprofng,gp-*}.1

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"

for f in COPYING COPYING3 COPYING3.LIB; do
	install -Dm0644 ../"${f}" \
		"$pkg/usr/share/doc/$program_name-$version"
done

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

