#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

sed -e 's/+01,234,567/+1,234,567 /' \
	-e 's/13.10Pd/13Pd/' \
	-i tests/tsprintf.c

./configure \
	--prefix=/usr \
	--disable-static     \
	--enable-thread-safe \
	--docdir=/usr/share/doc/"$program_name-$version"

make -j"$(NPROC)"
make html

make DESTDIR="$pkg" install
make DESTDIR="$pkg" install-html

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
for f in COPYING COPYING.LESSER; do
	install -Dm0644 "${f}" \
		"$pkg/usr/share/doc/$program_name-$version"
done

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

