#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

patch -Np1 -i "$cwd"/patches/coreutils-9.1-i18n-1.patch

autoreconf -fiv

FORCE_UNSAFE_CONFIGURE=1 ./configure \
	--prefix=/usr \
	--enable-no-install-program=kill,uptime

make -j"${NPROC}"

make DESTDIR="$pkg" install

install -dm0755 -o root -g root "$pkg/usr/sbin"
mv -v "$pkg"/usr/bin/chroot "$pkg"/usr/sbin

install -dm0755 -o root -g root \
	"$pkg"/usr/share/man/man8
mv -v "$pkg"/usr/share/man/man1/chroot.1 \
	"$pkg"/usr/share/man/man8/chroot.8

sed -i 's/"1"/"8"/' "$pkg"/usr/share/man/man8/chroot.8

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
	-e "shared object" | grep ELF | cut -d : -f 1 | \
	xargs strip --strip-unneeded 2> /dev/null || true

if [ -d "$pkg/usr/lib" ]; then
	find "$pkg"/usr/lib -name \*.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
	find "$pkg"/usr/libexec -name \*.la -delete
fi

install -dm0755 -o root -g root \
	"$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 COPYING \
	"$pkg/usr/share/doc/$program_name-$version/"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

