#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.gz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.gz"
cd "$program_name-$version"

chown root:root -R .

patch -Np1 -i "$cwd"/patches/bzip2-1.0.8-install_docs-1.patch

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile
sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

make -f Makefile-libbz2_so
make clean

make -j"$(NPROC)"

make DESTDIR="$pkg" PREFIX=/usr install

install -dm0755 -o root -g root "$pkg/usr/lib"

cp -av libbz2.so.* "$pkg"/usr/lib
ln -sv libbz2.so.1.0.8 "$pkg"/usr/lib/libbz2.so

install -dm0755 -o root -g root "$pkg/usr/bin"

cp -v bzip2-shared "$pkg"/usr/bin/bzip2

for i in "$pkg"/usr/bin/{bzcat,bunzip2}; do
	ln -sfv bzip2 $i
done

rm -fv "$pkg"/usr/lib/libbz2.a

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 LICENSE \
	"$pkg/usr/share/doc/$program_name-$version/"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name/patches"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"
cp patches/* \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/patches/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

