#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

export BUILD_ZLIB=False
export BUILD_BZIP2=0

sh Configure -des \
	-Dprefix=/usr \
	-Dvendorprefix=/usr \
	-Dprivlib=/usr/lib/perl5/"$version"/core_perl \
	-Darchlib=/usr/lib/perl5/"$version"/core_perl \
	-Dsitelib=/usr/lib/perl5/"$version"/site_perl \
	-Dsitearch=/usr/lib/perl5/"$version"/site_perl \
	-Dvendorlib=/usr/lib/perl5/"$version"/vendor_perl \
	-Dvendorarch=/usr/lib/perl5/"$version"/vendor_perl \
	-Dman1dir=/usr/share/man/man1 \
	-Dman3dir=/usr/share/man/man3 \
	-Dpager="/usr/bin/less -isR" \
	-Duseshrplib \
	-Dusethreads

make -j"$(NPROC)"

make DESTDIR="$pkg" install

unset BUILD_ZLIB BUILD_BZIP2

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
	-e "shared object" | grep ELF | cut -f 1 -d : | \
	xargs strip --strip-unneeded

if [ -d "$pkg/usr/lib" ]; then
	find "$pkg"/usr/lib -name *.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
	find "$pkg"/usr/libexec -name *.la -delete
fi

install -dm0755 -o root -g root \
	"$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 Artistic Copying \
	"$pkg/usr/share/doc/$program_name-$version/"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

