#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.gz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.gz"
cd "$program_name-$version"

chown root:root -R .

./configure \
	--prefix=/usr \
	--docdir=/usr/share/"$program_name-$version" \
	--disable-static

make -j"$(NPROC)"

make DESTDIR="$pkg" install

ln -sv flex "$pkg"/usr/bin/lex

install -dm0755 "$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 COPYING \
	"$pkg/usr/share/doc/$program_name-$version/"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

