#!/bin/sh -e

program_name="$(pwd)"
program_name="${program_name##*/}"

arch="$(uname -m)"
tag="droppkg"

IFS=" " read -r version build < "version"

if [ ! -f "$program_name-$version.tar.xz" ]; then
	read -r source < "sources"
	wget \
		--continue \
		"$source"
fi

cwd="$(pwd)"
pkg="$cwd/package-$program_name"

if [ -d "$pkg" ]; then
	rm -r "$pkg"
fi
mkdir "$pkg"

if [ -d "$cwd/$program_name-$version" ]; then
	rm -r "$cwd/$program_name-$version"
fi

tar xvf "$program_name-$version.tar.xz"
cd "$program_name-$version"

chown root:root -R .

patch -Np1 -i "$cwd"/patches/kbd-2.5.1-backspace-1.patch

sed -i '/RESIZECONS_PROGS=/s/yes/no/' configure
sed -i 's/resizecons.8 //' docs/man/man8/Makefile.in

./configure \
	--prefix=/usr \
	--disable-vlock

make -j"${NPROC}"

make DESTDIR="$pkg" install

find "$pkg" -print0 | xargs -0 file | grep -e "executable" \
	-e "shared object" | grep ELF | cut -d : -f 1 | \
	xargs strip --strip-unneeded 2> /dev/null || true

if [ -d "$pkg/usr/lib" ]; then
	find "$pkg"/usr/lib -name \*.la -delete
fi

if [ -d "$pkg/usr/libexec" ]; then
	find "$pkg"/usr/libexec -name \*.la -delete
fi

install -dm0755 -o root -g root \
	"$pkg/usr/share/doc/$program_name-$version"
install -Dm0644 COPYING \
	"$pkg/usr/share/doc/$program_name-$version/"

cp -R -v docs/doc/* \
	"$pkg"/usr/share/doc/"$program_name-$version"

mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name"
mkdir -p "$pkg/var/lib/db/tree/packages/installed/$program_name/patches/"
cd "$cwd"
cp build description sources version \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/"
cp patches/* \
	"$pkg/var/lib/db/tree/packages/installed/$program_name/patches/"

cd "$pkg"
/sbin/treepkg make \
	"$cwd/$program_name-$version-$arch-${build}_${tag}.tar.zstd"

